spring:
  application:
    name: server
  datasource:
    url: jdbc:h2:tcp://localhost/~/concert
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    #      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
